---
label: Product
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: file
  name: thumbnail
  label: thumbnail
- type: text
  name: year
  label: year
- type: list
  name: categories
  label: categories
  config:
    use_select: false
- name: price
  type: number
  label: price
  description: ''
  default: 8.42
  required: true
  config:
    min: 0
    max: 
    step: 0.1
